### ISSUE TITLE
"Unsupported or invalid disk type 2" booting Esxi images

### ISSUE THREAD

**Issue by AbcITAndrzej** [itiligent/OpenWRT-ImageBuilder#3]
Before starting Openwrt on ESXI, you should perform the following operation on the image created, e.g. "openwrt-23.05.5-custom-x86-64-generic-ext4-combined-efi.vmdk": vmkfstools -i openwrt-23.05.5-custom-x86-64-generic-ext4-combined-efi.vmdk new.vmdk Only the disk named "new.vmdk" can be added to the new image and the system can be started correctly. As: Guest OS version, you can select the type as "Other Linux (64-bit)".

**Comment by itiligent** [comment]
Could you please reference the specifc issue you are wanting to address by cloning the new image with vmkfstools? I've not had to do this and have various images that always started fine for me in all my testing (on Esxi 7.x and VMFS6)

**Comment by AbcITAndrzej** [comment]
Attempting to connect the original disk throws the following error (checked under esxi: 7.0 Update 3):

"[Failed to power on virtual machine aaaatest. Unsupported or invalid disk type 2 for 'scsi0:0'. Ensure that the disk has been imported. Click here for more details.](https://10.0.0.40/ui/#/host/vms/90/monitor/tasks/haTask-90-vim.VirtualMachine.powerOn-198048)"

Only executing "vmkfstools -i openwrt-23.05.5-custom-x86-64-generic-ext4-combined-efi.vmdk new.vmdk" causes the image to start correctly when we connect new.vmdk.

**Comment by itiligent** [comment]
I will try to replicate when I get the chance. There may be differences between the various type of OWRT images and how these are accepted by Esxi. I typically use virtualised squashfs images and have had no issue with these on Esxi, but "combined" images with ext4 or other nuances with the coversion on various Linux platforms might bring some other quirks.

**Comment by itiligent** [comment]
I was not able to replicate the error on Esxi 7 or 8. Closing.

**Comment by itiligent** [comment]
UPDATE:
Thanks to @AbcITAndrzej for pointing this out.  I'd previously not been able to replicate this until updating to more recent Esxi 7 & 8 builds..  I've also deleted unecessary info from this issue to keep it on point.

SOLUTION:

1.  Create a new VM as "Other 5.x Linux (64-bit)" 
2.  Upload the new vmdk image to  the the new VM's ESXi directory and run:
     `vmkfstools -i source.vmdk destintation.vmdk`
3. Point your new OWRT vm to `destintation.vmdk` using a SCSI or SAS controller
4. Finish any other VM configs and boot. 
5. If you still cant boot, check to see if secure boot is enbled on the VM. (Depending on your HW BIOS setup and TPM this can also prevent booting.)
